name: intelligence_demo_hr_tech
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  auto_route: ^9.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intelligence: ^0.0.1-dev.2
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: 
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
